spring:
  datasource:
    url: jdbc:postgresql://10.1.203.12:5432/dcblock
    username: apiserver
    password: digicap12#$
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
     springframework:
       web:
         filter:
           CommonsRequestLoggingFilter: DEBUG

allow_remotes:
  - 127.0.0.1
  - 10.1.203.12
  - 10.1.62.1

api_version: application/vnd.digicap.v1+json

purchase_list_viewer_server: http://10.51.6.20:9090/my_order

admin_server: http://localhost:8080/api

random_uri_expired_minute: 60