spring:
  datasource:

logging:
  level:
    org:
     springframework:
       web:
         filter:
           CommonsRequestLoggingFilter: DEBUG

allow_remotes:
  - 127.0.0.1
  - 10.1.203.12
  - 10.1.62.1

api_version: application/vnd.digicap+json;version=1.0

# Must added Last Slash of URI
purchase_list_viewer_server: http://localhost:8080/

random_uri_expired_minute: 60