spring:
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10 
      connectionTimeout: 30000

logging:
  level:
    org:
     springframework:
       web:
         filter:
           CommonsRequestLoggingFilter: DEBUG

allow_remotes:
  - 127.0.0.1
  - 10.1.203.12
  - 10.1.62.1

api_version: application/vnd.digicap.v1+json

purchase_list_viewer_server: http://10.51.6.20:8080/my_order

admin_server: http://10.1.91.101:8090/api

random_uri_expired_minute: 60